# toml config to send only those lang, region to channel

[config]
national = [
    'english',
    'hindi',
    'sanskrit',
    'tamil',
    # 'urdu',
    # 'assamese',
    # 'bengali',
    # 'dogri',
    # 'gujarati',
    # 'kannada',
    # 'kashmiri',
    # 'konkani',
    # 'malayalam',
    # 'marathi',
    # 'nepali',
    # 'odia',
    # 'punjabi',
    # 'telugu',
]

local = [
    'chennai-tamil',
    'tiruchirapalli-tamil',
    # 'agartala-kokborok',
    # 'agartala-bengali',
    # 'ahmedabad-gujarati',
    # 'ahmedabad-sindhi',
    # 'aizawl-mizo',
    # 'aurangabad-marathi',
    # 'aurangabad-urdu',
    # 'bangalore-kannada',
    # 'bhopal-hindi',
    # 'bhuj-gujarati',
    # 'calicut-malayalam',
    # 'chandigarh-hindi',
    # 'chandigarh-punjabi',
    # 'cuttack-odia',
    # 'dehradun-hindi',
    # 'dharwad-kannada',
    # 'dibrugarh-assamese',
    # 'gangtok-nepali',
    # 'gangtok-lepcha',
    # 'gangtok-bhutia',
    # 'gorakhpur-hindi',
    # 'gorakhpur-bhojpuri',
    # 'guwahati-assamese',
    # 'guwahati-karbi',
    # 'guwahati-nepali',
    # 'guwahati-bodo',
    # 'hyderabad-telugu',
    # 'hyderabad-urdu',
    # 'imphal-manipuri',
    # 'itanagar-hindi',
    # 'itanagar-english',
    # 'jaipur-hindi',
    # 'jaipur-rajasthani',
    # 'jammu-gojri',
    # 'jammu-dogri',
    # 'kohima-nagamese',
    # 'kohima-english',
    # 'kolkata-bengali',
    # 'kurseong-nepali',
    # 'leh-ladakhi',
    # 'lucknow-hindi',
    # 'lucknow-urdu',
    # 'mumbai-marathi',
    # 'nagpur-marathi',
    # 'panaji-konkani',
    # 'patna-hindi',
    # 'patna-maithili',
    # 'pudducherry-tamil',
    # 'pune-marathi',
    # 'raipur-chhatisgar',
    # 'raipur-hindi',
    # 'ranchi-hindi',
    # 'sambalpur-sambalpuri',
    # 'shillong-jaintia',
    # 'shillong-english',
    # 'shillong-khasi',
    # 'shillong-garo',
    # 'shimla-hindi',
    # 'silchar-bengali',
    # 'thiruvanantapuram-malayalam',
    # 'vijayawada-telugu',
    # 'visakhapatnam-telugu'
]
